import {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Box,
  Camera,
  Car,
  ChartNoAxesCombined,
  CheckCircle2,
  ChevronRight,
  CircleDollarSign,
  CircleX,
  ClipboardList,
  Database,
  Eraser,
  Flame,
  Folder,
  Gamepad2,
  HeartPulse,
  Home,
  Info,
  Lightbulb,
  LogOut,
  Moon,
  Palette,
  Pencil,
  PiggyBank,
  Pin,
  Plus,
  ReceiptText,
  RefreshCw,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Stethoscope,
  Sun,
  Trash2,
  TrendingUp,
  Utensils,
  WalletCards,
  X,
} from 'lucide-react';
import type { LucideIcon, LucideProps } from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  alert: AlertTriangle,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-down': ArrowUpDown,
  'badge-check': BadgeCheck,
  'bar-chart': BarChart3,
  book: BookOpen,
  box: Box,
  camera: Camera,
  car: Car,
  chart: ChartNoAxesCombined,
  check: CheckCircle2,
  'chevron-right': ChevronRight,
  'circle-dollar': CircleDollarSign,
  'circle-x': CircleX,
  clipboard: ClipboardList,
  database: Database,
  eraser: Eraser,
  flame: Flame,
  folder: Folder,
  gamepad: Gamepad2,
  health: HeartPulse,
  home: Home,
  info: Info,
  lightbulb: Lightbulb,
  logout: LogOut,
  moon: Moon,
  palette: Palette,
  pencil: Pencil,
  'piggy-bank': PiggyBank,
  pin: Pin,
  plus: Plus,
  receipt: ReceiptText,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shield: ShieldAlert,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'sliders-horizontal': SlidersHorizontal,
  stethoscope: Stethoscope,
  sun: Sun,
  trash: Trash2,
  trend: TrendingUp,
  utensils: Utensils,
  wallet: WalletCards,
  x: X,
};

interface AppIconProps extends Omit<LucideProps, 'ref'> {
  name: string;
}

export default function AppIcon({ name, size = 18, strokeWidth = 2, className = '', ...props }: AppIconProps) {
  const IconComponent = ICONS[name] || Pin;
  return <IconComponent className={`app-icon ${className}`.trim()} aria-hidden="true" focusable="false" size={size} strokeWidth={strokeWidth} {...props} />;
}
